build:
  version: "2.0"

products:
  message: "Welcome to toko online products related QA APIs "
  contactDetails:
    name: "Fahrul - QA Lead"
    email: "fahrul@gmail.com.com"
  onCallSupport:
    - 22222222222222
    - 22222222222222