spring:
  data:
    mongodb:
      uri: "mongodb://product:product@localhost:27018/product?authSource=admin"
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"




redisConfig:
  host: "localhost"
  port: 6370



info:
  app:
    name: "products"
    description: "Toko online products Application"
    version: "1.0.0"


build:
  version: "3.0"

products:
  message: "Welcome to toko online products related local APIs "
  contactDetails:
    name: "Robi Nurhidayat - Developer"
    email: "robi@gmail.com"
  onCallSupport:
    - 000000000000
    - 000000000000