spring:
  data:
    mongodb:
      uri: "mongodb://product:product@DB_PRODUCT:27017/product?authSource=admin"
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

info:
  app:
    name: "products"
    description: "Toko online products Application"
    version: "1.0.0"


build:
  version: "1.0"

products:
  message: "Welcome to toko online products related prod APIs "
  contactDetails:
    name: "Bagus perdana- Product Owner"
    email: "bagus@gmail.com"
  onCallSupport:
    - 11111111111111
    - 11111111111111