build:
  version: "3.0"

products:
  message: "Welcome to toko online products related local APIs "
  contactDetails:
    name: "Robi Nurhidayat - Developer"
    email: "robi@gmail.com"
  onCallSupport:
    - 000000000000
    - 000000000000